### ISSUE TITLE
operand: unable to generate "ANDQ $-32, DI"

### ISSUE THREAD

**Issue by klauspost** [mmcloughlin/avo#116]
I am porting the runtime memmove. I have come across [`ANDQ $-32, DI`](https://github.com/golang/go/blob/master/src/runtime/memmove_amd64.s#L334) which I suspect get translated to `0xffffffffffffffe0`.

I have not found a way to enter that instruction. All fail with "ANDQ: bad operands"

I have tried `ANDQ(I8(-32), dst)`, `ANDQ(I64(-32), dst)`, `ANDQ(U64(0xffffffffffffffe0), dst)`.

**Comment by klauspost** [comment]
The only thing I can do is 

```
MOVQ(U64(0xffffffffffffffe0), tmp)
ANDQ(tmp, dst)
```

**Comment by mmcloughlin** [comment]
Hmm, this isn't very user friendly. I agree the `I*` operand forms are not behaving as you would expect.

The `ANDQ` instruction takes `imm8` or `imm32` immediate operands (https://godoc.org/github.com/mmcloughlin/avo/x86#ANDQ). I think the negative integer values are all being treated as `imm64` operand by `avo` (not desirable). The following will be interpreted correctly as an `imm32` operand.

```go
ANDQ(U32(0xffffffe0), x)
```

Hope this fixes your issue in the short term? I should probably look into making the `I*` operands do what you'd expect.

**Comment by klauspost** [comment]
Is ANDQ sign extending? Then I guess adding it as a U8 would work.

**Comment by klauspost** [comment]
Hmmm... This will emit `ANDQ    $0xe0, AX` which the assembler encodes as an imm32, making it NOT work.

**Comment by mmcloughlin** [comment]
Yes `ANDQ` is sign extending. Does the `U32` version in my previous comment work? `ANDQ(U32(0xffffffe0), x)`

**Comment by klauspost** [comment]
Yes, it does. Now I have a fairly close equivalent of the memmove: https://github.com/klauspost/compress/pull/186/files#diff-60d6e6209d2fc7873851f07b946a5dc7R1010

Non-AVX uses REP, but the AVX version should be the same, but without supporting overlapping in+output. Fuzz tests check out at least :)

**Comment by klauspost** [comment]
Maybe you should open a repo for generators for common functions like this :)

**Comment by mmcloughlin** [comment]
> Maybe you should open a repo for generators for common functions like this :)

Interesting you should say that, I've been thinking it would be nice to have some sort of "standard library" for `avo`. I mentioned this in the "Future" section of the Gophercon talk: https://youtu.be/WaD8sNqroAw?t=2172

**Comment by mmcloughlin** [comment]
Closing this particular issue. Issues #118 and #18 are still open to cover some of the underlying problem here.
