### ISSUE TITLE
pass: allow labels following each other

### ISSUE THREAD

**Issue by klauspost** [mmcloughlin/avo#122]
When generating complex stuff it is a bit annoying that it isn't possible to have two labels follow each other.

[Example](https://github.com/klauspost/compress/blob/7ca389b3e8e5bb3e3fb12deb7d28c9b24f01443b/s2/gen.go#L1060) where I need to be able to jump back to the beginning of a piece of inlined code.

This gets annoying when I have [a caller](https://github.com/klauspost/compress/blob/7ca389b3e8e5bb3e3fb12deb7d28c9b24f01443b/s2/gen.go#L675) that may or may not have code between itself and the previous label. This forces me to insert a [`NOP`](https://github.com/klauspost/compress/blob/7ca389b3e8e5bb3e3fb12deb7d28c9b24f01443b/s2/gen.go#L1062).

I am wondering if there are technical problems in lifting this restriction?

**Comment by mmcloughlin** [comment]
Yeah I have no problem relaxing this constraint, just needs a slight tweak to how the CFG pass works.

There wasn't a strong motivation at the time, it just seemed like something you'd _usually_ want to avoid. But it's probably better implemented as an optional warning or linter than a compilation error.

I'll work on this change soon, probably tomorrow.

**Comment by klauspost** [comment]
Yeah, completely agree. It is not a big deal, but sometimes it is quite tricky to work around.
