### ISSUE TITLE
build: warn/error if Mem.Index is set but Mem.Scale is 0

### ISSUE THREAD

**Issue by klauspost** [mmcloughlin/avo#125]
An easy mistake to do is to create a `Mem{Base:x, Index:Idx}` and forget to set the Scale.

I can't see the `Scale:0` being useful, so maybe just error?

**Comment by mmcloughlin** [comment]
Yes this seems reasonable, and not too hard to add.

My expectation was that people would use the helper methods on `Mem` instead, which I think would make this error less likely. https://godoc.org/github.com/mmcloughlin/avo/operand#Mem.Idx

**Comment by klauspost** [comment]
It is mostly when combining them from registers, IE `MOVQ(Mem{Base:reg, Index:reg2, Disp: 4}, reg)` or similar.

`Mem.Idx()` has its own quirks. Mainly, if you consider a "Mem" struct as a reference to memory. Calling `Idx` will override the internals and will not be a reference to the new memory, if the index was set previously.

Mostly this is tricky when passing around memory references, since it may or may not be something where `Idx(x,y)` gives you an offset. Basically the only way to be sure would to do:

```
func foo(a Mem) {
  if a.Index !=nil {
    x := GP64()
    LEAQ(a, x)
    a = Mem{Base: x}
   }
  a = a.Idx(23, 4)
}
```
If you don't do the LEAQ your function could not accept any parameters. I am not saying you should change this, but it is something that is a source for mistakes - unlike Mem.(Offset) which adds it.
