### ISSUE TITLE
Document how to refer to a symbol in the same package

### ISSUE THREAD

**Issue by bwesterb** [mmcloughlin/avo#141]
It's unclear to me how to refer to a symbol in the same package.

Perhaps this is obvious, as #42 is about supporting it for *external* packages, but I could not figure it out.

**Comment by mmcloughlin** [comment]
Apologies for the glacial response on this one.

Does this comment https://github.com/mmcloughlin/avo/issues/42#issuecomment-506992578 answer your question? It's definitely ugly, and not well documented, but it should work.

**Comment by bwesterb** [comment]
Yes, that works. Thank you.

**Comment by mmcloughlin** [comment]
Okay good. #42 remains open to actually fix this.
