### ISSUE TITLE
Guess package by target directory or make it overridable

### ISSUE THREAD

**Issue by bwesterb** [mmcloughlin/avo#147]
To prevent `avo` ending up in `go.mod` and `go.sum` of a library that uses `avo` to generate its code, we can separate it out as follows

```
subpkg/
  uses-avo.go
  avo/
    go.sum
    go.mod.        # separate go.mod that will include avo
    avo-file.go
```

But where to put the generated assembly and stubs?  If we put it in the `avo` folder then accessing it will incur an indirect import of avo again.  If we put it in the `subpkg` folder, then the package name is wrong: the stubs file will have package name `avo`.

A workaround is to rename the `avo` folder to `subpkg`, but that is confusing, so we can put it in `avo/subpkg` top-level.  That only works if there is no other subpackage named `subpkg` in the library.  So the foolproof workaround is to put it in `subpkg/avo/subpkg` which is not pretty.

Instead I'd like to suggest one of two changes:

1. Add a `-pkg` flag that allows one to specify the package name generated.
2. Use the directory of the stubs file to guess the package name instead of the directory of the source go file.

**Comment by mmcloughlin** [comment]
Yes this is a reasonable request, and has come up before #68 . I'll try to get this done soon.
