### ISSUE TITLE
missing sse2 movdqa/movdqu instruments

### ISSUE THREAD

**Issue by choleraehyq** [mmcloughlin/avo#157]
There are VMOVDQA/VMOVDQU/MASKMOVDQU/VMASKMOVDQU, but missing MOVDQA/MOVDQU.

**Comment by mmcloughlin** [comment]
I believe these instructions have different names in Go assembler. To see this take a look at the x86 CSV (fields are explained in the [`golang.org/x/arch/x86/x86spec`](https://godoc.org/golang.org/x/arch/x86/x86spec) documentation).

For these instructions, `MOVDQA` is `MOVO`:

https://github.com/mmcloughlin/avo/blob/34d153690af87c7adf87412bf92db14ec427e532/internal/data/x86.v0.2.csv#L823

`MOVDQU` is `MOVOU`:

https://github.com/mmcloughlin/avo/blob/34d153690af87c7adf87412bf92db14ec427e532/internal/data/x86.v0.2.csv#L825-L826

These are both supported by `avo`:

https://github.com/mmcloughlin/avo/blob/443f81d771042b019379ae4bfcd0a591cb47c88a/build/zinstructions.go#L7930-L7939
https://github.com/mmcloughlin/avo/blob/443f81d771042b019379ae4bfcd0a591cb47c88a/build/zinstructions.go#L7984-L7993

And before you say anything, yes, Go assembly is weird sometimes!

**Comment by choleraehyq** [comment]
@mmcloughlin I see, thanks for your explanation!
