### ISSUE TITLE
bug: Function signatures generate incorrect argument size

### ISSUE THREAD

**Issue by Yawning** [mmcloughlin/avo#195]
avo: `TEXT("Example", NOSPLIT|NOFRAME, "func(x *uint64, y uint32)")`
asm: `TEXT ·Example(SB), NOSPLIT|NOFRAME, $0-16`

`go vet` complains `./bug.s:6:1: [amd64] Example: wrong argument size 16; expected $...-12`

This may very well be `go vet` being silly, but I'm not sure if there's supposed to be padding there or not.

**Comment by mmcloughlin** [comment]
Sorry I missed this. I've seen something similar to this before and I wonder if it's related: golang/go#39220.

**Comment by mmcloughlin** [comment]
Ah... I might have responded to quickly there. This could be an `avo` issue. I remember that the specifics of function argument/return value padding are a little subtle and poorly documented. I'll have to take a look and get back to you.

**Comment by mmcloughlin** [comment]
Okay, I'm almost certain this is the same bug as #191, just fixed in #212. Let me check.

**Comment by mmcloughlin** [comment]
Yes this seems to have been the exact same thing. I landed a regression test in #214.

**Comment by mmcloughlin** [comment]
I believe this is fixed, with an extensive test added in #216. Tagged release v0.3.1.
