### ISSUE TITLE
tests/thirdparty: segmentio/asm broken under avx-512

### ISSUE THREAD

**Issue by mmcloughlin** [mmcloughlin/avo#229]
The `segmentio/asm` third-party test is broken under the current AVX-512 work #217 #20. For the reasoning see https://github.com/mmcloughlin/avo/issues/20#issuecomment-962549267.

I will disable the test on the branch for now, and this serves as a reminder to make the fix and re-enable once the work is landed.

cc @kalamay

**Comment by kalamay** [comment]
Hi @mmcloughlin I've just created a branch pulling in this version of Avo here: https://github.com/segmentio/asm/pull/59

There's a little bit of a chicken-or-egg situation as far as released versions go, but we should be fine pulling in this [`x-avx512`](https://github.com/mmcloughlin/avo/tree/x-avx512) branch for now and updating once it's merged.

**Comment by mmcloughlin** [comment]
Thanks! Yeah I added a skip option in the third-party tests #228 so I was able to disable your test on the branch. Once it lands we can land your branch on your end.
