### ISSUE TITLE
doc: broken link to Filippo's live coding session

### ISSUE THREAD

**Issue by arl** [mmcloughlin/avo#236]
Hi,
It seems the link to Fillipo's live coding session of AVO, which is present in the README, is dead.
I've looked for another link to it but I couldn't find it.

**Comment by mmcloughlin** [comment]
Ah yes, it seems to be down.

@FiloSottile Do you think you could revive https://videos.filippo.io, or post the videos elsewhere?

**Comment by FiloSottile** [comment]
Ah, yeah, that didn't last. I kinda wish some service would take my money to simply host videos at a URL I control. Maybe I should just embed Vimeo into static pages on my site.

**Comment by FiloSottile** [comment]
Alright, just gave Vimeo some money to host it for me, and gave up on owning the URL.

Should be ready soon at https://vimeo.com/679848853!

**Comment by arl** [comment]
I confirm. it's there now, awesome, thanks @FiloSottile

**Comment by mmcloughlin** [comment]
Updated! Thanks for the quick response @FiloSottile :)
