### ISSUE TITLE
Getting `CL` register for variable shifts

### ISSUE THREAD

**Issue by klauspost** [mmcloughlin/avo#238]
I am struggling to get the `CL` register for a variable shift.

I have tried a bazillion combinations. The closest I have gotten is:

```
		shift := reg.CL
		LEAQ(Mem{Base: a, Index: b, Scale: 1}, shift.As64()) 
		ROLQ(shift, value)
```
Which gives `non physical register found`. 

Using `RCX` and `ROLQ(shift.As8L(), value)` just gives `bad operands`.

I have looked through the repo for an example, but I couldn't find one. This seems like a show-stopper.

**Comment by klauspost** [comment]
OK, the `non physical register found` comes from a  `MOVB(state.As8H(), n.As8L())`. Closing for now.

**Comment by mmcloughlin** [comment]
Hmm, does your program work now? The `non physical register found` error generally shouldn't happen.

**Comment by klauspost** [comment]
@mmcloughlin I presume it is because the assigned register doesn't have 8 bit high.
