### ISSUE TITLE
How to return a bool value?

### ISSUE THREAD

**Issue by cocotyty** [mmcloughlin/avo#336]
I found that there is no `bool` type checked here:
  https://github.com/mmcloughlin/avo/blob/master/build/zmov.go

**Comment by mmcloughlin** [comment]
I think this should be fixed by #341. Included in [`v0.5.0`](https://github.com/mmcloughlin/avo/releases/tag/v0.5.0), which I just pushed.

Please reopen this if you're still seeing problems.

Thanks for reporting the issue.

**Comment by cocotyty** [comment]
Thank you for your awesome project. 😀
