### ISSUE TITLE
lint: ensure package-level doc strings

### ISSUE THREAD

**Issue by mmcloughlin** [mmcloughlin/avo#38]
Is there a `golangci-lint` configuration option or another linter that will ensure all packages have package-level doc?

Related to #9

**Comment by jirfag** [comment]
hi! you can use golangci-lint flag/option `exclude-use-default=false` to disable default exclude list with this warning, and golint will report it

**Comment by dgryski** [comment]
The latest `staticcheck` ensures every package has a package-level comment.

**Comment by mmcloughlin** [comment]
I think I have `staticcheck` enabled via `megacheck` in `golangci-lint`. It must not be the latest version since it doesn't appear to be linting for package doc strings. I took the "hack up a bash script" route.
