### ISSUE TITLE
Cannot generate stubs

### ISSUE THREAD

**Issue by jeschkies** [mmcloughlin/avo#386]
When I run the simple add example I get the following error

```
› go run ./pkg/asm.go -out ./pkg/add.s -stubs ./pkg/stub.go
3:9: expected 'IDENT', found 'go'
exit status 1
```

The stub file is empty.

**Comment by mmcloughlin** [comment]
Please can you share the contents of these files?

**Comment by jeschkies** [comment]
Thanks for the quick reply. The code is from the README. the simple add example https://github.com/jeschkies/go-memmem/tree/karsten/ci/pkg/add. It worked once I've moved it into the `pkg/add` folder.

**Comment by mmcloughlin** [comment]
Glad it works now!
