### ISSUE TITLE
Assembly generation printing floating point literals without decimal causes invalid interpretation

### ISSUE THREAD

**Issue by dmgard** [mmcloughlin/avo#387]
`DATA someF32<>+0(SB)/4, $(1.0)` will be interpreted correctly as `1.0f`
`DATA someF32<>+0(SB)/4, $(1)` will seemingly be loaded as `0.0f`

If a `DATA` section is specified using, for example, `F32(1.0)`, avo renders it as `$(1)`, which the Go assembler seems to interpret as an integer.

Manually changing the assembly to `$(1.0)` works.

**Comment by mmcloughlin** [comment]
I think this should be fixed with #393. Let me know if there's any other issues! Sorry for the slow response. Thanks again.
