### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by cristaloleg** [mmcloughlin/avo#415]
Looks like v0.5.0 was more than a year ago however, there are many updates for the last year. Are there blockers to make a new release?

Thanks!

**Comment by mmcloughlin** [comment]
Thanks for prompting. Just pushed [`v0.6.0`](https://github.com/mmcloughlin/avo/releases/tag/v0.6.0).

**Comment by cristaloleg** [comment]
Amazing, huge thanks!
