### ISSUE TITLE
question: pointer to struct in a different package

### ISSUE THREAD

**Issue by mmcloughlin** [mmcloughlin/avo#53]
Migrating [question from reddit](https://www.reddit.com/r/golang/comments/adwmdj/mmcloughlinavo_generate_x86_assembly_with_go/eecubg3).

Hi, again thanks for your time :) I've run into a slight problem which might just be me not understanding the docs. Is there a way of using `Param("")` and `.Field()` through a pointer? I've got:

```go
Package("github.com/jamiec7919/vermeer/core")
TEXT("intersectBoxes", NOSPLIT, "func (ray *Ray, boxes *[4*3*2]float32, hits *[4]int32, t *[4]float32)")
Doc("intersectBoxes evaluates the given..")
// MOVSS (AX),X3 // X3 = ray.O[0]
rayOX := Load(Param("ray").Field("O").Index(0), XMM())
```

The Ray type (in core) is something like:

```
type Ray struct {
O [3]float32
}
```

But I can't work out how to get a reference to `O[0]` etc. via the Param. Keep getting 'not struct type' etc. I tried various combos like `Base()` and `Index(0)` just in case but no good :)

Also it didn't seem to like me including the package name in the func signature:

```
TEXT("intersectBoxes", NOSPLIT, "func (ray *core.Ray, boxes *[4*3*2]float32, hits *[4]int32, t *[4]float32)")
```

The asm code is not in the core package, but another package that references a public type from core.

Errors out with:

```
intersect_asm.go:12: eval:1:12: undeclared name: core
intersect_asm.go:16: unknown variable "ray"
intersect_asm.go:20: unknown variable "ray"
exit status 1
```

**Comment by jamiec7919** [comment]
Now I've actually read through the docs I see that my usage of Package() was wrong, it's only for setting the package that the generated file should be part of.

**Comment by mmcloughlin** [comment]
This kind of feedback is really valuable, thank you. I'm also excited that you're using `avo` :)

Unfortunately the short answer is that `avo` does not currently support your use case. I have filed issues to think about these specifically.

* The `Param` mechanism does not enable access to struct fields via a pointer #54
* Struct references in function signatures are assumed to be in the same package as the function #55

In the short term, how many fields do you need from the `Ray` struct? If it's just `O [3]float32` I would recommend passing that directly. Since your function is private maybe it's okay to have a more ugly interface? Would this work for you?

**Comment by jamiec7919** [comment]
There are several other fields that are used, although that will be a workaround but this is used in a tight inner loop so extra stack copying may cause performance degradation (can't say for sure as haven't measured).   

I could emulate the existing asm with its fixed offsets into the Ray structure but I think I'll need to edit/delete the generated stubs to include the external package.  

Will experiment more.

**Comment by mmcloughlin** [comment]
@jamiec7919 I have put up a pull request that I think might resolve one half of your issue, specifically accessing external types #55.

To begin with I was trying to make the following work:

```
Package("github.com/user/repo/pkg")
Import("github.com/user/repo/other")
TEXT("FuncName", NOSPLIT, "func(arg other.Struct) int")
```

I'm sure this is possible somehow, but right now I don't see how to do it without some ugly gymnastics involving the `go/types` and `x/tools/go/packages` packages. I spent far too long thinking about this.

It occurred to me that this would be far easier if the user writes the stubs themselves (only for cases like this). The pull request provides an alternative method of opening an `avo` function called `Implement`.

```
Package("github.com/user/repo/pkg")
Implement("FuncName")
```

You have to write the stub for `FuncName` yourself but that's not too hard. The pull request has a working example.

I think this is quite elegant, and requires not much extra code.

Any thoughts appreciated.

**Comment by jamiec7919** [comment]
Yes that does seem like a neat workaround for the stubs, it avoids any manual work after regenerating the .s  (in fact in my case the stubs are already there since its a straight port of the manually written asm) - haven't tried it yet but will try to get to it this week so I have a fully implemented function with no manual interventions.

**Comment by jamiec7919** [comment]
Actually thinking about it, could you not provide a different way to specify signatures?  We could import the desired packages and pass a value in which avo could deconstruct to get the offsets, fields etc.  not sure on the practicalities but seems like an option?

**Comment by mmcloughlin** [comment]
> I take it though that this is just a fix for the stubs and avo will still not be able to access fields etc. via Param for types defined in other packages? (ignoring the access through pointer thing)

This is not just a fix for the stubs. `avo` will be able to access the fields via `Param`. See the `ext` example. We have a struct in an external package

https://github.com/mmcloughlin/avo/blob/eb225e9d2ca0419d680f4394d3d76494f6746d1e/examples/ext/ext/ext.go#L4-L9

This is used in a function signature:

https://github.com/mmcloughlin/avo/blob/eb225e9d2ca0419d680f4394d3d76494f6746d1e/examples/ext/stub.go#L2-L7

Then referenced from the `avo` generator

https://github.com/mmcloughlin/avo/blob/eb225e9d2ca0419d680f4394d3d76494f6746d1e/examples/ext/asm.go#L9-L16

Note that we are able to access field `B` of the function argument `e`.

Work is still required to enable pointer dereference #54.

**Comment by mmcloughlin** [comment]
> Actually thinking about it, could you not provide a different way to specify signatures? We could import the desired packages and pass a value in which avo could deconstruct to get the offsets, fields etc. not sure on the practicalities but seems like an option?

Actually I considered using `reflect` for signatures early on and dropped the idea in favor of `go/types`. One major reason was that you can't get function/method parameter names with `reflect` golang/go#12384. However `reflect` may still be useful in other ways, thanks for the reminder.

**Comment by jamiec7919** [comment]
Very nice :)

**Comment by mmcloughlin** [comment]
I think #61 will address the pointer dereference issue.

**Comment by jamiec7919** [comment]
Hiya, just confirming that these changes have made it so I can directly port my code into avo :)  The generated code is pretty much identical to what I wrote manually (modulo register renames).  It's not checked in anywhere yet but I'll be extending it and probably writing some more elaborate code for QBVH traversals when I can work out function calls and maybe calling through an interface get sadded.  Wish I had more time or I'd dig in to see if I could help out.

Only thing I might be missing is making the generated functions private, I found I had to make it public for the stub to be detected - I can understand why this might be and it's not a massive problem.

Took me a bit to work out how to keep the dereference around (rather than reloading it each time), currently I'm doing this:

ray := Dereference(Param("ray"))

Px := Load(ray.Field("P").Field("X"),XMM())

and reusing the ray variable throughout the rest of the function to get the rest of the fields, seems to work ok (only loads the reference into a register once and reuses it throughout) but I don't know if that's guaranteed correct?

**Comment by mmcloughlin** [comment]
> Hiya, just confirming that these changes have made it so I can directly port my code into avo :)

This is really exciting! Thanks for being an early-adopter :)

> Only thing I might be missing is making the generated functions private, I found I had to make it public for the stub to be detected - I can understand why this might be and it's not a massive problem.

Hmm, this isn't the behavior I'd expect. Are you able to share more about this?

> Took me a bit to work out how to keep the dereference around (rather than reloading it each time), currently I'm doing this:
> 
> ray := Dereference(Param("ray"))
> 
> Px := Load(ray.Field("P").Field("X"),XMM())
> 
> and reusing the ray variable throughout the rest of the function to get the rest of the fields, seems to work ok (only loads the reference into a register once and reuses it throughout) but I don't know if that's guaranteed correct?

This is actually the correct way to do this. See the example:

https://github.com/mmcloughlin/avo/blob/9eb409b935dcee298b49327fddb3a4e3caa6ecea/examples/args/asm.go#L102-L105

The reason is that a `Dereference()` call will actually produce a `MOVQ` instruction to place the pointer in a register. If you called it multiple times you'd produce multiple redundant move instructions.

**Comment by jamiec7919** [comment]
> This is actually the correct way to do this. See the example:
> 
> The reason is that a `Dereference()` call will actually produce a `MOVQ` instruction to place the pointer in a register. If you called it multiple times you'd produce multiple redundant move instructions.

Ah that's great, that's the behaviour I was seeing.  I didn't notice that example/args had been updated which would have saved some time - I was a little confused at first as I didn't realise Dereference was available as a package level function and I was trying to use Component.Dereference(reg) like:

rayReg := Load(Param("ray"),GP64())
Px := Load(Param("ray").Dereference(rayReg).Field()...  

This did work but glad I figured out the proper way :)

**Comment by jamiec7919** [comment]
> Hmm, this isn't the behavior I'd expect. Are you able to share more about this?

Yep but might be a bit long winded as I'm not very good at being succinct :)

Ok so I have a package with files:

github.com/jamiec7919/vermeer/qbvh
- asm.go
- intersect.go
- (others...)

asm.go is new with the avo code:

```go
// +build asm

package main

import (
	. "github.com/mmcloughlin/avo/build"
	. "github.com/mmcloughlin/avo/operand"
)

func main() {
	Package("github.com/jamiec7919/vermeer/qbvh")
	Implement("intersectBoxes")

	ray := Dereference(Param("ray"))

	Px := Load(ray.Field("P").Field("X"), XMM())
	SHUFPS(U8(0), Px, Px)
	Dinvx := Load(ray.Field("Dinv").Field("X"), XMM())
	SHUFPS(U8(0), Dinvx, Dinvx)

	box := Load(Param("boxes"), GP64())
	t1 := XMM()
	MOVAPS(Mem{Base: box}, t1)
	SUBPS(Px, t1)
	MULPS(Dinvx, t1)

	t2 := XMM()
	MOVAPS(Mem{Base: box, Disp: 48}, t2) // Could we get the mem via the type?
	SUBPS(Px, t2)
	MULPS(Dinvx, t2)

	tmin := XMM()
	tmax := XMM()
	MOVAPS(t1, tmin)
	MOVAPS(t1, tmax)
	MINPS(t2, tmin)
	MAXPS(t2, tmax)

	Py := Load(ray.Field("P").Field("Y"), XMM())
	SHUFPS(U8(0), Py, Py)
	Dinvy := Load(ray.Field("Dinv").Field("Y"), XMM())
	SHUFPS(U8(0), Dinvy, Dinvy)

	MOVAPS(Mem{Base: box, Disp: 16}, t1)
	SUBPS(Py, t1)
	MULPS(Dinvy, t1)

	MOVAPS(Mem{Base: box, Disp: 16 + 48}, t2) // Could we get the mem via the type?
	SUBPS(Py, t2)
	MULPS(Dinvy, t2)

	tmp0 := XMM()

	MOVAPS(t1, tmp0)
	MINPS(t2, t1)
	MAXPS(tmp0, t2)

	MINPS(t2, tmax)
	MAXPS(t1, tmin)

	Pz := Load(Dereference(Param("ray")).Field("P").Field("Z"), XMM())
	SHUFPS(U8(0), Pz, Pz)
	Dinvz := Load(Dereference(Param("ray")).Field("Dinv").Field("Z"), XMM())
	SHUFPS(U8(0), Dinvz, Dinvz)

	MOVAPS(Mem{Base: box, Disp: 32}, t1)
	SUBPS(Pz, t1)
	MULPS(Dinvz, t1)

	MOVAPS(Mem{Base: box, Disp: 32 + 48}, t2) // Could we get the mem via the type?
	SUBPS(Pz, t2)
	MULPS(Dinvz, t2)

	//tmp0 := XMM()

	MOVAPS(t1, tmp0)
	MINPS(t2, t1)
	MAXPS(tmp0, t2)

	MINPS(t2, tmax)
	MAXPS(t1, tmin)

	tNear := XMM()
	XORPS(tNear, tNear)
	MAXPS(tmin, tNear) // tNear = max(tmin,0)

	t := Load(Param("t"), GP64())
	MOVAPS(tNear, Mem{Base: t})

	hits := Load(Param("hits"), GP64())
	CMPPS(tmax, tNear, U8(0x2)) // tmax >= tNear?
	MOVAPS(tNear, Mem{Base: hits})

	RET()

	Generate()
}
```

In intersect.go I have the stub and the generate, plus the code which uses the asm routine:

```go
// Copyright 2019 The Vermeer Light Tools Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package qbvh

import (
	"github.com/jamiec7919/vermeer/core"
	m "github.com/jamiec7919/vermeer/math"
)

//go:generate go run asm.go -out asm_amd64.s

//go:nosplit
//go:noescape
func intersectBoxes(ray *core.Ray, boxes *[4 * 3 * 2]float32, hits *[4]int32, t *[4]float32)

///SNIP

// Trace traverses the tree and calls prim.TraceElems for any non-empty leaf encountered.
//go:nosplit
func Trace(qbvh []Node, prim Primitive, ray *core.Ray, sg *core.ShaderContext) bool {

///SNIP

  // Use asm routine                    
  intersectBoxes(ray, &qbvh[node].Boxes, &ray.Task.Traversal.Hits, &ray.Task.Traversal.T)

///SNIP
}
```

Now as above this doesn't work, when I do go generate (in the qbvh directory) I get:

> D:\Projects\go\src\github.com\jamiec7919\vermeer\qbvh>go generate
> asm.go:12: could not find function "intersectBoxes"
> asm.go:14: no active function
> asm.go:14: unknown variable "ray"
> asm.go:16: unknown variable "ray"
> asm.go:17: no active function
> asm.go:18: unknown variable "ray"
> asm.go:19: no active function
> asm.go:21: no active function
> asm.go:21: unknown variable "boxes"
> asm.go:23: no active function
> too many errors
> exit status 1
> intersect.go:13: running "go": exit status 1

If I change the name of intersectBoxes to IntersectBoxes it all works fine.

**Comment by mmcloughlin** [comment]
> Yep but might be a bit long winded as I'm not very good at being succinct :)

Thanks for sharing. I am pretty sure I know where the problem is. If you are _generating_ stubs, then private functions work fine. But since you are using an existing stubs file, I am guessing that the problem is that the package loader is only loading exported symbols. I need to confirm, but I think there may be a relatively easy fix for this.

**Comment by jamiec7919** [comment]
I suspected it was due to the package loader only seeing public symbols, if there's a fix that would be good, although for my use case it isn't critical :)

**Comment by mmcloughlin** [comment]
I think #63 fixed the issue of `Implement` not working with private functions.

**Comment by jamiec7919** [comment]
Looks like that's done it, I can now generate that function as private :)    Might as well close this issue since you've answered everything now - thanks!

**Comment by mmcloughlin** [comment]
Great! Please open another issue if something else comes up.
