### ISSUE TITLE
`MOVQ(Imm(0), Mem{Base: p})` not supported.

### ISSUE THREAD

**Issue by dgryski** [mmcloughlin/avo#67]
The equivalent code works fine in PeachPy.

https://github.com/dgryski/go-chaskey/blob/master/core_amd64.s#L56

```
package main

import (
        . "github.com/mmcloughlin/avo/build"
        . "github.com/mmcloughlin/avo/operand"
)

func main() {
        Package("github.com/dgryski/bug")

        TEXT("bug", NOSPLIT, "func(p *uint64)")

        p := GP64()
        Load(Param("p"), p)

        MOVQ(Imm(0), Mem{Base: p})

        RET()
        Generate()
}
```

Running this I get:
```
bug.go:17: MOVQ: bad operands
```

**Comment by mmcloughlin** [comment]
Oh dear, I think you may be running up against #18. This is ugly.

Under the hood the types are actually `U8`, `U16`, .... `Imm()` is a "convenience" that works most of the time. It selects the smallest bitsize that would contain the provided value, which is `U8` in this case.

In the instruction database the supported form is `imm32 m64`. So your code works if you replace `Imm` with `U32`.

**Comment by mmcloughlin** [comment]
From an offline discussion, I think this is resolved.
