### ISSUE TITLE
gotypes: allow for struct array definitions

### ISSUE THREAD

**Issue by meyer9** [mmcloughlin/avo#77]
Allow for indexing into structs like this:
```go
type a [6]uint64
```

I believe this is a problem with:
https://github.com/mmcloughlin/avo/blob/master/gotypes/components.go#L146

which should call Underlying() before checking if it's an array.

**Comment by mmcloughlin** [comment]
Oh, yes I'm pretty sure you're right! I'll put out a fix tonight.

**Comment by mmcloughlin** [comment]
I believe this is resolved. Please reopen if not.
